refactor: move tools -> .tools

diff --git a/templates/managed/project/go/files/project/Taskfile.go.yml b/templates/managed/project/go/files/project/Taskfile.go.yml
--- a/templates/managed/project/go/files/project/Taskfile.go.yml
+++ b/templates/managed/project/go/files/project/Taskfile.go.yml
@@ -10,10 +10,10 @@ vars:
   TOOLS_DIR:
     sh: |
       git_root=$(git rev-parse --show-toplevel 2>/dev/null)
-      if [ $? -eq 0 ] && [ -d "$git_root/tools" ]; then
-        echo "$git_root/tools"
+      if [ $? -eq 0 ] && [ -d "$git_root/.tools" ]; then
+        echo "$git_root/.tools"
       else
-        echo "Error: Could not find tools directory in git root" >&2
+        echo "Error: Could not find .tools directory in git root" >&2
         exit 1
       fi
   GO_TOOL_CMD: go tool -modfile={{.TOOLS_DIR}}/go.mod
@@ -70,7 +70,7 @@ tasks:
       - find . -name "*.go" | xargs -P $(nproc) gopls check
 
   install-gopls:
-    desc: Install stylua using version from tools/Cargo.toml
+    desc: Install stylua using version from .tools/Cargo.toml
     aliases: ["install"]
     cmds:
       - go install golang.org/x/tools/gopls@latest
